.ifndef SCR_SEQ_T29_H_
.definelabel SCR_SEQ_T29_H_, 0

.equ _EV_scr_seq_T29_000, 0
.equ _EV_scr_seq_T29_001, 1
.equ _EV_scr_seq_T29_002, 2
.equ _EV_scr_seq_T29_003, 3
.equ _EV_scr_seq_T29_004, 4
.equ _EV_scr_seq_T29_005, 5
.equ _EV_scr_seq_T29_006, 6
.equ _EV_scr_seq_T29_007, 7
.equ _EV_scr_seq_T29_008, 8
.equ _EV_scr_seq_T29_009, 9
.equ _EV_scr_seq_T29_010, 10
.equ _EV_scr_seq_T29_011, 11
.equ _EV_scr_seq_T29_012, 12
.equ _EV_scr_seq_T29_013, 13
.equ _EV_scr_seq_T29_014, 14
.equ _EV_scr_seq_T29_015, 15
.equ _EV_scr_seq_T29_016, 16
.equ _EV_scr_seq_T29_017, 17
.equ _EV_scr_seq_T29_018, 18
.equ _EV_scr_seq_T29_019, 19

.equ obj_T29_gsoldman1, 0
.equ obj_T29_gswoman1, 1
.equ obj_T29_gsman1, 2
.equ obj_T29_rgyaradosu, 3
.equ obj_T29_wataru, 8
.equ obj_T29_gsman1_2, 9
.equ obj_T29_follower_mon_static_dragonite, 10
.equ obj_T29_monstarball, 14
.equ obj_T29_monstarball_2, 15
.equ obj_T29_tree, 16
.equ obj_T29_tree_2, 17
.equ obj_T29_tree_3, 18
.equ obj_T29_monstarball_3, 19
.equ obj_T29_gsleader7, 20
.equ obj_T29_brains2, 21

.endif //SCR_SEQ_T29_H_
