.ifndef SCR_SEQ_R35_H_
.definelabel SCR_SEQ_R35_H_, 0

.equ _EV_scr_seq_R35_000, 0
.equ _EV_scr_seq_R35_001, 1
.equ _EV_scr_seq_R35_002, 2
.equ _EV_scr_seq_R35_003, 3
.equ _EV_scr_seq_R35_004, 4
.equ _EV_scr_seq_R35_005, 5

.equ obj_R35_badman, 4
.equ obj_R35_juggrer, 5
.equ obj_R35_seaman, 6
.equ obj_R35_gsman2, 7
.equ obj_R35_policeman, 8
.equ obj_R35_monstarball, 9
.equ obj_R35_tree, 10
.equ obj_R35_bonguri, 11
.equ obj_R35_gsmiddleman1, 12
.equ obj_R35_fire, 13
.equ obj_R35_monstarball_2, 14
.equ obj_R35_follower_mon_static_pidgey, 15
.equ obj_R35_3622, 0
.equ obj_R35_gsfighter, 1

.endif //SCR_SEQ_R35_H_
