.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0
.equ _EV_scr_seq_EVERYWHERE_001, 1
.equ _EV_scr_seq_EVERYWHERE_002, 2
.equ _EV_scr_seq_EVERYWHERE_003, 3
.equ _EV_scr_seq_EVERYWHERE_004, 4
.equ _EV_scr_seq_EVERYWHERE_005, 5
.equ _EV_scr_seq_EVERYWHERE_006, 6
.equ _EV_scr_seq_EVERYWHERE_007, 7
.equ _EV_scr_seq_EVERYWHERE_008, 8
.equ _EV_scr_seq_EVERYWHERE_009, 9
.equ _EV_scr_seq_EVERYWHERE_010, 10

.equ obj_EVERYWHERE_workman, 2
.equ obj_EVERYWHERE_monstarball, 3
.equ obj_EVERYWHERE_artist, 0

.endif //SCR_SEQ_EVERYWHERE_H_
