.ifndef SCR_SEQ_R38_H_
.definelabel SCR_SEQ_R38_H_, 0

.equ _EV_scr_seq_R38_000, 0
.equ _EV_scr_seq_R38_001, 1
.equ _EV_scr_seq_R38_002, 2
.equ _EV_scr_seq_R38_003, 3
.equ _EV_scr_seq_R38_004, 4
.equ _EV_scr_seq_R38_005, 5

.equ obj_R38_gsman3, 0
.equ obj_R38_gsman2, 1
.equ obj_R38_gswoman2, 3
.equ obj_R38_bonguri, 5
.equ obj_R38_monstarball, 6
.equ obj_R38_3936, 7
.equ obj_R38_4070, 2
.equ obj_R38_4070_2, 4
.equ obj_R38_gsgirl1, 8

.endif //SCR_SEQ_R38_H_
