.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0
.equ _EV_scr_seq_EVERYWHERE_001, 1
.equ _EV_scr_seq_EVERYWHERE_002, 2
.equ _EV_scr_seq_EVERYWHERE_003, 3
.equ _EV_scr_seq_EVERYWHERE_004, 4
.equ _EV_scr_seq_EVERYWHERE_005, 5
.equ _EV_scr_seq_EVERYWHERE_006, 6
.equ _EV_scr_seq_EVERYWHERE_007, 7
.equ _EV_scr_seq_EVERYWHERE_008, 8
.equ _EV_scr_seq_EVERYWHERE_009, 9
.equ _EV_scr_seq_EVERYWHERE_010, 10

.equ obj_EVERYWHERE_monstarball, 0
.equ obj_EVERYWHERE_monstarball_2, 1
.equ obj_EVERYWHERE_monstarball_3, 2
.equ obj_EVERYWHERE_rock, 3
.equ obj_EVERYWHERE_rock_2, 4
.equ obj_EVERYWHERE_rock_3, 5
.equ obj_EVERYWHERE_brains3, 6
.equ obj_EVERYWHERE_princess, 7
.equ obj_EVERYWHERE_gswoman3, 8
.equ obj_EVERYWHERE_gswoman3_2, 8
.equ obj_EVERYWHERE_juggrer, 9
.equ obj_EVERYWHERE_woman3, 10
.equ obj_EVERYWHERE_2669, 11
.equ obj_EVERYWHERE_2669_2, 12

.endif //SCR_SEQ_EVERYWHERE_H_
