.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0
.equ _EV_scr_seq_EVERYWHERE_001, 1
.equ _EV_scr_seq_EVERYWHERE_002, 2
.equ _EV_scr_seq_EVERYWHERE_003, 3
.equ _EV_scr_seq_EVERYWHERE_004, 4
.equ _EV_scr_seq_EVERYWHERE_005, 5
.equ _EV_scr_seq_EVERYWHERE_006, 6
.equ _EV_scr_seq_EVERYWHERE_007, 7
.equ _EV_scr_seq_EVERYWHERE_008, 8
.equ _EV_scr_seq_EVERYWHERE_009, 9
.equ _EV_scr_seq_EVERYWHERE_010, 10

.equ obj_EVERYWHERE_rock, 0
.equ obj_EVERYWHERE_ice, 1
.equ obj_EVERYWHERE_ice_2, 2
.equ obj_EVERYWHERE_ice_3, 3
.equ obj_EVERYWHERE_ice_4, 4
.equ obj_EVERYWHERE_ice_5, 5
.equ obj_EVERYWHERE_ice_6, 6
.equ obj_EVERYWHERE_monstarball, 7
.equ obj_EVERYWHERE_monstarball_2, 8

.endif //SCR_SEQ_EVERYWHERE_H_
