.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0
.equ _EV_scr_seq_EVERYWHERE_001, 1
.equ _EV_scr_seq_EVERYWHERE_002, 2
.equ _EV_scr_seq_EVERYWHERE_003, 3
.equ _EV_scr_seq_EVERYWHERE_004, 4
.equ _EV_scr_seq_EVERYWHERE_005, 5
.equ _EV_scr_seq_EVERYWHERE_006, 6
.equ _EV_scr_seq_EVERYWHERE_007, 7
.equ _EV_scr_seq_EVERYWHERE_008, 8
.equ _EV_scr_seq_EVERYWHERE_009, 9
.equ _EV_scr_seq_EVERYWHERE_010, 10

.equ obj_EVERYWHERE_rock, 0
.equ obj_EVERYWHERE_monstarball, 1
.equ obj_EVERYWHERE_monstarball_2, 2
.equ obj_EVERYWHERE_monstarball_3, 3
.equ obj_EVERYWHERE_monstarball_4, 4
.equ obj_EVERYWHERE_monstarball_5, 5
.equ obj_EVERYWHERE_monstarball_6, 6
.equ obj_EVERYWHERE_monstarball_7, 7
.equ obj_EVERYWHERE_monstarball_8, 10
.equ obj_EVERYWHERE_monstarball_9, 11
.equ obj_EVERYWHERE_juggrer, 12
.equ obj_EVERYWHERE_explore, 13
.equ obj_EVERYWHERE_assistantm, 14
.equ obj_EVERYWHERE_woman3, 15
.equ obj_EVERYWHERE_gsman3, 17
.equ obj_EVERYWHERE_gswoman3, 18
.equ obj_EVERYWHERE_mount, 8
.equ obj_EVERYWHERE_workman, 9
.equ obj_EVERYWHERE_workman_2, 9

.endif //SCR_SEQ_EVERYWHERE_H_
