.ifndef SCR_SEQ_R34_H_
.definelabel SCR_SEQ_R34_H_, 0

.equ _EV_scr_seq_R34_000, 0
.equ _EV_scr_seq_R34_001, 1
.equ _EV_scr_seq_R34_002, 2
.equ _EV_scr_seq_R34_003, 3
.equ _EV_scr_seq_R34_004, 4
.equ _EV_scr_seq_R34_005, 5
.equ _EV_scr_seq_R34_006, 6
.equ _EV_scr_seq_R34_007, 7
.equ _EV_scr_seq_R34_008, 8
.equ _EV_scr_seq_R34_009, 9
.equ _EV_scr_seq_R34_010, 10
.equ _EV_scr_seq_R34_011, 11
.equ _EV_scr_seq_R34_012, 12
.equ _EV_scr_seq_R34_013, 13
.equ _EV_scr_seq_R34_014, 14
.equ _EV_scr_seq_R34_015, 15

.equ obj_R34_gsboy2, 0
.equ obj_R34_man3, 2
.equ obj_R34_policeman, 3
.equ obj_R34_explore, 4
.equ obj_R34_gswoman3, 5
.equ obj_R34_gswoman3_2, 6
.equ obj_R34_gswoman3_3, 7
.equ obj_R34_3605, 8
.equ obj_R34_gsoldman1, 10
.equ obj_R34_var_1, 11
.equ obj_R34_2684, 12
.equ obj_R34_monstarball, 14
.equ obj_R34_gsmiddleman1, 15
.equ obj_R34_monstarball_2, 1
.equ obj_R34_4070, 9
.equ obj_R34_4067, 16
.equ obj_R34_4065, 17

.endif //SCR_SEQ_R34_H_
