.ifndef SCR_SEQ_EVERYWHERE_H_
.definelabel SCR_SEQ_EVERYWHERE_H_, 0

.equ _EV_scr_seq_EVERYWHERE_000, 0
.equ _EV_scr_seq_EVERYWHERE_001, 1
.equ _EV_scr_seq_EVERYWHERE_002, 2
.equ _EV_scr_seq_EVERYWHERE_003, 3
.equ _EV_scr_seq_EVERYWHERE_004, 4
.equ _EV_scr_seq_EVERYWHERE_005, 5
.equ _EV_scr_seq_EVERYWHERE_006, 6
.equ _EV_scr_seq_EVERYWHERE_007, 7
.equ _EV_scr_seq_EVERYWHERE_008, 8
.equ _EV_scr_seq_EVERYWHERE_009, 9
.equ _EV_scr_seq_EVERYWHERE_010, 10

.equ obj_EVERYWHERE_monstarball, 0
.equ obj_EVERYWHERE_monstarball_2, 1
.equ obj_EVERYWHERE_monstarball_3, 2
.equ obj_EVERYWHERE_monstarball_4, 3
.equ obj_EVERYWHERE_breakrock, 4
.equ obj_EVERYWHERE_breakrock_2, 5
.equ obj_EVERYWHERE_breakrock_3, 6
.equ obj_EVERYWHERE_breakrock_4, 7
.equ obj_EVERYWHERE_breakrock_5, 8

.endif //SCR_SEQ_EVERYWHERE_H_
