.ifndef SCR_SEQ_D43R0102_H_
.definelabel SCR_SEQ_D43R0102_H_, 0

.equ _EV_scr_seq_D43R0102_000, 0
.equ _EV_scr_seq_D43R0102_001, 1
.equ _EV_scr_seq_D43R0102_002, 2
.equ _EV_scr_seq_D43R0102_003, 3
.equ _EV_scr_seq_D43R0102_004, 4

.equ obj_D43R0102_monstarball, 0
.equ obj_D43R0102_monstarball_2, 1
.equ obj_D43R0102_monstarball_3, 2
.equ obj_D43R0102_rock, 3
.equ obj_D43R0102_rock_2, 4
.equ obj_D43R0102_oldman1, 5
.equ obj_D43R0102_itako_, 6
.equ obj_D43R0102_fire, 7
.equ obj_D43R0102_follower_mon_crobat, 8
.equ obj_D43R0102_follower_mon_crobat_2, 8
.equ obj_D43R0102_follower_mon_crobat_3, 8

.endif //SCR_SEQ_D43R0102_H_
