.ifndef SCR_SEQ_W40_H_
.definelabel SCR_SEQ_W40_H_, 0

.equ _EV_scr_seq_W40_000, 0
.equ _EV_scr_seq_W40_001, 1
.equ _EV_scr_seq_W40_002, 2
.equ _EV_scr_seq_W40_003, 3
.equ _EV_scr_seq_W40_004, 4
.equ _EV_scr_seq_W40_005, 5
.equ _EV_scr_seq_W40_006, 6
.equ _EV_scr_seq_W40_007, 7
.equ _EV_scr_seq_W40_008, 8
.equ _EV_scr_seq_W40_009, 9

.equ obj_W40_gsswimmerm, 2
.equ obj_W40_gsswimmerw, 3
.equ obj_W40_gswoman1, 4
.equ obj_W40_gsmiddleman1, 5
.equ obj_W40_monstarball, 6
.equ obj_W40_monstarball_2, 7

.endif //SCR_SEQ_W40_H_
