.ifndef SCR_SEQ_R31_H_
.definelabel SCR_SEQ_R31_H_, 0

.equ _EV_scr_seq_R31_000, 0
.equ _EV_scr_seq_R31_001, 1
.equ _EV_scr_seq_R31_002, 2
.equ _EV_scr_seq_R31_003, 3
.equ _EV_scr_seq_R31_004, 4
.equ _EV_scr_seq_R31_005, 5
.equ _EV_scr_seq_R31_006, 6
.equ _EV_scr_seq_R31_007, 7
.equ _EV_scr_seq_R31_008, 8
.equ _EV_scr_seq_R31_009, 9
.equ _EV_scr_seq_R31_010, 10

.equ obj_R31_gsman1, 0
.equ obj_R31_tree, 1
.equ obj_R31_gsbigman, 2
.equ obj_R31_tree_2, 3
.equ obj_R31_gsboy1, 4
.equ obj_R31_gsboy3, 5
.equ obj_R31_monstarball, 6
.equ obj_R31_monstarball_2, 7
.equ obj_R31_bonguri, 8
.equ obj_R31_girl1, 9
.equ obj_R31_4067, 10
.equ obj_R31_4061, 11
.equ obj_R31_4063, 12
.equ obj_R31_4062, 13

.endif //SCR_SEQ_R31_H_
