#include "../include/types.h"
#include "../include/constants/sndseq.h"
#include "../include/constants/species.h"
#include "../include/constants/trainerclass.h"

// Table seems to combine animation in column 1 with music in column 2, 0xFFFF for no special animation

u16 MainMusicComboTable[][2] =
{
    [ANIM_MUSIC_COMBO_FALKNER] = {0xC, SEQ_G5_GYM_LEADER },
    [ANIM_MUSIC_COMBO_BUGSY] = {0xD, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_WHITNEY] = {0xE, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_MORTY] = {0xF, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_JASMINE] = {0x10, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_CHUCK] = {0x11, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_PRYCE] = {0x12, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_CLAIR] = {0x13, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_GARDENIA] = {0x14, SEQ_SINNOH_LEADER},
    [ANIM_MUSIC_COMBO_MARLON] = {0x15, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_PLASMA] = {0x0, SEQ_VS_PLASMA_FIGHT},
    [ANIM_MUSIC_COMBO_CYNTHIA] = {0x17, SEQ_VS_CYNTHIA},
    [ANIM_MUSIC_COMBO_DARKRAI] = {0x18, SEQ_BATTLE_AGAINST_DUSKNOIR},
    [ANIM_MUSIC_COMBO_BROKEN] = {0x19, SEQ_GS_VS_GYMREADER_KANTO},
    [ANIM_MUSIC_COMBO_HANNAH] = {0x1A, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_BLUE] = {0x1B, SEQ_GS_VS_GYMREADER_KANTO},
    [ANIM_MUSIC_COMBO_STEVEN] = {0xFFFF, SEQ_VS_STEVEN}, //was 0x1D
    [ANIM_MUSIC_COMBO_KOGA] = {0x1E, SEQ_GS_VS_GYMREADER},
    [ANIM_MUSIC_COMBO_BRUNO] = {0x1F, SEQ_GS_VS_GYMREADER},
    [ANIM_MUSIC_COMBO_KAREN] = {0x20, SEQ_GS_VS_GYMREADER},
    [ANIM_MUSIC_COMBO_ZINZOLIN] = {0xFFFF, SEQ_CYRUS_COMPLETE},// was 0x21,LANCE
    [ANIM_MUSIC_COMBO_MIASMA] = {0xFFFF, SEQ_XENOBLADE_YWKON},//WAS 0X1C
    [ANIM_MUSIC_COMBO_RAIKOU] = {0xFFFF, SEQ_G5_GYM_LEADER},
    [ANIM_MUSIC_COMBO_ENTEI] = {0xFFFF, SEQ_GS_VS_ENTEI},
    [ANIM_MUSIC_COMBO_SUICUNE] = {0xFFFF, SEQ_GS_VS_SUICUNE},
    [ANIM_MUSIC_COMBO_HO_OH] = {0x23, SEQ_GS_VS_HOUOU},
    [ANIM_MUSIC_COMBO_LUGIA] = {0x24, SEQ_GS_VS_LUGIA},
    [ANIM_MUSIC_COMBO_WEATHER_TRIO] = {0x22, SEQ_GS_VS_KODAI},
    [ANIM_MUSIC_COMBO_MEWTWO_LATI_TWINS] = {0x22, SEQ_GS_VS_NORAPOKE_KANTO},
    [ANIM_MUSIC_COMBO_COLRESS] = {0xFFFF, SEQ_COLRESS_MINI},//WAS 0X27
    [ANIM_MUSIC_SHADOW_TRIAD] = {0xFFFF, SEQ_XENOBLADE_YWKON},
    [ANIM_MUSIC_COMBO_SATURN] = {0x29, SEQ_CYRUS_COMPLETE},
    [ANIM_MUSIC_COMBO_CYRUS] = {0x2A, SEQ_CYRUS_COMPLETE},
    [ANIM_MUSIC_COMBO_MARS] = {0x2B, SEQ_CYRUS_COMPLETE},
    [ANIM_MUSIC_COMBO_GIOVANNI] = {0x2C, SEQ_GS_VS_ROCKET},
    [ANIM_MUSIC_COMBO_JOHTO_TRAINER_1] = {0x25, SEQ_GS_VS_TRAINER},
    [ANIM_MUSIC_COMBO_JOHTO_TRAINER_2] = {0x25, SEQ_GS_VS_TRAINER},
    [ANIM_MUSIC_COMBO_JOHTO_TRAINER_3] = {0x26, SEQ_GS_VS_TRAINER},
    [ANIM_MUSIC_COMBO_JOHTO_WILD_BATTLE_38] = {0x26, SEQ_GS_VS_NORAPOKE},
    [ANIM_MUSIC_COMBO_GHETSIS] = {0x25, SEQ_VS_GHETSIS},
    [ANIM_MUSIC_COMBO_GYM_LEADER_38] = {0x26, SEQ_GS_VS_GYMREADER},
    [ANIM_MUSIC_COMBO_JOHTO_TRAINER] = {0xFFFF, SEQ_GS_VS_TRAINER},
    [ANIM_MUSIC_COMBO_JOHTO_WILD_THEME] = {0xFFFF, SEQ_GS_VS_NORAPOKE},
    [ANIM_MUSIC_COMBO_TRAINER_N] = {0x2D, SEQ_VS_N_2},
    [ANIM_MUSIC_COMBO_RED] = {0x2E, SEQ_GS_VS_CHAMP},
    // (***END OF VANILLA ENTRIES***)
    [ANIM_MUSIC_COMBO_MINIBOSS] = {0xFFFF, SEQ_XENOBLADE_YWKON},
};

// format is one byte for trainer class, then one byte for combo (combo increments by 4 because each combo is four bytes long)

u8 TrainerClassToMusicCombo[][2] =
{
    {TRAINERCLASS_VOLKNER, ANIM_MUSIC_COMBO_FALKNER*4},
    {TRAINERCLASS_FLINT, ANIM_MUSIC_COMBO_BUGSY*4},
    {TRAINERCLASS_LEADER_WHITNEY, ANIM_MUSIC_COMBO_WHITNEY*4},
    {TRAINERCLASS_LEADER_MORTY, ANIM_MUSIC_COMBO_MORTY*4},
    {TRAINERCLASS_LEADER_JASMINE, ANIM_MUSIC_COMBO_JASMINE*4},
    {TRAINERCLASS_LEADER_CHUCK, ANIM_MUSIC_COMBO_CHUCK*4},
    {TRAINERCLASS_LEADER_PRYCE, ANIM_MUSIC_COMBO_PRYCE*4},
    {TRAINERCLASS_LEADER_CLAIR, ANIM_MUSIC_COMBO_CLAIR*4},
    {TRAINERCLASS_LEADER_BROCK, ANIM_MUSIC_COMBO_GARDENIA*4},
    {TRAINERCLASS_MISTY, ANIM_MUSIC_COMBO_MARLON*4},
    {TRAINERCLASS_PLASMA_M, ANIM_MUSIC_COMBO_PLASMA*4},
    {TRAINERCLASS_CYNTHIA_OPPONENT, ANIM_MUSIC_COMBO_CYNTHIA*4},
    {TRAINERCLASS_DARKRAI, ANIM_MUSIC_COMBO_DARKRAI*4},
    {TRAINERCLASS_GHETSIS, ANIM_MUSIC_COMBO_GHETSIS*4},
    {TRAINERCLASS_HANNAH, ANIM_MUSIC_COMBO_HANNAH*4},
    {TRAINERCLASS_SAGE_ROOD, ANIM_MUSIC_COMBO_ZINZOLIN*4},
    {TRAINERCLASS_STEVEN, ANIM_MUSIC_COMBO_STEVEN*4},
    {TRAINERCLASS_ELITE_FOUR_KOGA, ANIM_MUSIC_COMBO_KOGA*4},
    {TRAINERCLASS_ELITE_FOUR_BRUNO, ANIM_MUSIC_COMBO_BRUNO*4},
    {TRAINERCLASS_ELITE_FOUR_KAREN, ANIM_MUSIC_COMBO_KAREN*4},
    {TRAINERCLASS_ZINZOLIN, ANIM_MUSIC_COMBO_ZINZOLIN*4},
    {TRAINERCLASS_PLASMA_F, ANIM_MUSIC_COMBO_PLASMA*4},
    {TRAINERCLASS_LT_SURGE, ANIM_MUSIC_COMBO_RAIKOU*4},
    {TRAINERCLASS_MIASMA, ANIM_MUSIC_COMBO_MIASMA*4},
    {TRAINERCLASS_SHADOW_TRIAD, ANIM_MUSIC_SHADOW_TRIAD*4},
    {TRAINERCLASS_SATURN, ANIM_MUSIC_COMBO_SATURN*4},
    {TRAINERCLASS_MARS, ANIM_MUSIC_COMBO_MARS*4},
    {TRAINERCLASS_COLRESS, ANIM_MUSIC_COMBO_COLRESS*4},
    {TRAINERCLASS_GALACTIC_F, ANIM_MUSIC_COMBO_PLASMA*4},
    {TRAINERCLASS_TRAINER_N, ANIM_MUSIC_COMBO_TRAINER_N*4},
    {TRAINERCLASS_PKMN_TRAINER_RED, ANIM_MUSIC_COMBO_RED*4},
    // (***END OF VANILLA ENTRIES***)

    //IRIDIUM ENTRIES
    //{TRAINERCLASS_ROUGHNECK, ANIM_MUSIC_COMBO_MINIBOSS*4},
};

struct MonBattleMusic
{
    u16 species:10;
    u16 combo:6;
};

struct MonBattleMusic PokemonBattleMusic[] =
{
    {.species = SPECIES_RAIKOU,   .combo = ANIM_MUSIC_COMBO_RAIKOU},
    {.species = SPECIES_ENTEI,    .combo = ANIM_MUSIC_COMBO_ENTEI},
    {.species = SPECIES_SUICUNE,  .combo = ANIM_MUSIC_COMBO_SUICUNE},
    {.species = SPECIES_LUGIA,    .combo = ANIM_MUSIC_COMBO_LUGIA},
    {.species = SPECIES_HO_OH,    .combo = ANIM_MUSIC_COMBO_HO_OH},
    {.species = SPECIES_GROUDON,  .combo = ANIM_MUSIC_COMBO_WEATHER_TRIO},
    {.species = SPECIES_KYOGRE,   .combo = ANIM_MUSIC_COMBO_WEATHER_TRIO},
    {.species = SPECIES_RAYQUAZA, .combo = ANIM_MUSIC_COMBO_WEATHER_TRIO},
    {.species = SPECIES_MEWTWO,   .combo = ANIM_MUSIC_COMBO_MEWTWO_LATI_TWINS},
    {.species = SPECIES_LATIOS,   .combo = ANIM_MUSIC_COMBO_MEWTWO_LATI_TWINS},
    {.species = SPECIES_LATIAS,   .combo = ANIM_MUSIC_COMBO_MEWTWO_LATI_TWINS},
    // (***END VANILLA ENTRIES***)
};

struct TrainerMusic
{
    u16 class;
    u16 music1;
    u16 music2;
};

struct TrainerMusic sTrainerEncounterMusicParam[] = // cues which music sequence occurs upon eyes meeting
{
    {.class = TRAINERCLASS_YOUNGSTER, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_LASS, .music1 = SEQ_GS_EYE_K_SHOUJO, .music2 = SEQ_GS_EYE_K_SHOUJO},
    {.class = TRAINERCLASS_CAMPER, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_PICNICKER, .music1 = SEQ_GS_EYE_K_SHOUJO, .music2 = SEQ_GS_EYE_K_SHOUJO},
    {.class = TRAINERCLASS_BUG_CATCHER, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_TWINS, .music1 = SEQ_GS_EYE_K_SHOUJO, .music2 = SEQ_GS_EYE_K_SHOUJO},
    {.class = TRAINERCLASS_HIKER, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_FISHERMAN, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_BLACK_BELT, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_POKEFAN_M, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_POKEFAN, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_ACE_TRAINER_M_GS, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_ACE_TRAINER_F_GS, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_BIRD_KEEPER_GS, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_JUGGLER, .music1 = SEQ_GS_EYE_J_AYASHII, .music2 = SEQ_GS_EYE_J_AYASHII},
    {.class = TRAINERCLASS_GENTLEMAN, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_BEAUTY, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_POLICEMAN, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_SWIMMER_M, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_SWIMMER_F, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_SAILOR, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_TRAINER_N, .music1 = SEQ_GS_EYE_MAIKO, .music2 = SEQ_GS_EYE_MAIKO},
    {.class = TRAINERCLASS_PSYCHIC_M, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_GUITARIST, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_GALACTIC_M, .music1 = SEQ_GS_EYE_ROCKET, .music2 = SEQ_GS_EYE_ROCKET},
    {.class = TRAINERCLASS_SKIER, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_SCHOOL_KID_M, .music1 = SEQ_GS_EYE_J_SHOUNEN, .music2 = SEQ_GS_EYE_J_SHOUNEN},
    {.class = TRAINERCLASS_GALACTIC_F, .music1 = SEQ_GS_EYE_ROCKET, .music2 = SEQ_GS_EYE_ROCKET},
    {.class = TRAINERCLASS_BURGLAR, .music1 = SEQ_GS_EYE_J_AYASHII, .music2 = SEQ_GS_EYE_J_AYASHII},
    {.class = TRAINERCLASS_FIREBREATHER, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_BIKER, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_POKE_MANIAC, .music1 = SEQ_GS_EYE_J_AYASHII, .music2 = SEQ_GS_EYE_J_AYASHII},
    {.class = TRAINERCLASS_TEACHER, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_SUPER_NERD, .music1 = SEQ_GS_EYE_J_AYASHII, .music2 = SEQ_GS_EYE_J_AYASHII},
    {.class = TRAINERCLASS_SAGE, .music1 = SEQ_GS_EYE_BOUZU, .music2 = SEQ_GS_EYE_BOUZU},
    {.class = TRAINERCLASS_MEDIUM, .music1 = SEQ_GS_EYE_BOUZU, .music2 = SEQ_GS_EYE_BOUZU},
    {.class = TRAINERCLASS_SCIENTIST_GS, .music1 = SEQ_GS_EYE_ROCKET, .music2 = SEQ_GS_EYE_J_AYASHII},
    {.class = TRAINERCLASS_BOARDER, .music1 = SEQ_GS_EYE_K_AYASHII, .music2 = SEQ_GS_EYE_K_AYASHII},
    {.class = TRAINERCLASS_SAGE_BRONIUS, .music1 = SEQ_GS_EYE_K_SHOUNEN, .music2 = SEQ_GS_EYE_K_SHOUNEN},
    {.class = TRAINERCLASS_MIASMA, .music1 = SEQ_GS_EYE_J_SHOUJO, .music2 = SEQ_GS_EYE_J_SHOUJO},
    {.class = TRAINERCLASS_PLASMA_F, .music1 = SEQ_PLASMA_EYE_BASIC_BANK, .music2 = SEQ_PLASMA_EYE_BASIC_BANK},
    {.class = TRAINERCLASS_PLASMA_M, .music1 = SEQ_PLASMA_EYE_BASIC_BANK, .music2 = SEQ_PLASMA_EYE_BASIC_BANK},
    {.class = TRAINERCLASS_SATURN, .music1 = SEQ_GS_EYE_ROCKET, .music2 = SEQ_GS_EYE_ROCKET},
    {.class = TRAINERCLASS_MARS, .music1 = SEQ_GS_EYE_ROCKET, .music2 = SEQ_GS_EYE_ROCKET},
    {.class = TRAINERCLASS_PLASMA_M, .music1 = SEQ_PLASMA_EYE_BASIC_BANK, .music2 = SEQ_PLASMA_EYE_BASIC_BANK},
};
